#!/bin/bash

#whoami
#ls -lh /var/lib
chown -R openfire:openfire /etc/openfire /var/lib/openfire
#ls /etc/openfire
#ls /var/lib/openfire
df -h
/usr/bin/supervisord -n -c /etc/supervisor/conf.d/docker.conf 
#/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -server -DopenfireHome=/usr/share/openfire -Dopenfire.lib.dir=/usr/share/openfire/lib -classpath /usr/share/openfire/lib/startup.jar -jar /usr/share/openfire/lib/startup.jar


